cascade:
  # Configure blog posts
  - _target:
      path: /post/**
    pager: true
    show_date: true
    editable: false
    reading_time: true
    commentable: false
    show_related: true
    show_breadcrumb: true
    share: true
    header:
      navbar:
        enable: true

cascade:
  # Configure blog posts
  - _target:
      path: /project/**
    pager: true
    show_date: true
    editable: false
    reading_time: true
    commentable: false
    show_related: true
    show_breadcrumb: false
    share: true
    header:
      navbar:
        enable: true
